### ISSUE TITLE
i18n functionality via gettext

### ISSUE THREAD

**Issue by Sebi55** [alanvardy/exzeitable#208]
**Is your feature request related to a problem? Please describe.**
The whole table functionality is great but as many sites are served in multiple languages it is necessary that also the table buttons, fields and placeholders can be translatted.

**Describe the solution you'd like**
I want to be able to somewhere save separate files for each language to replace the default english text depended on the provided language of Phoenix.

**Additional context**
It would be great if I could use the normal gettext functionality in form of a further .po file.
If that is not possible it would be great to override maybe the default messages like Pow does it: https://hexdocs.pm/pow/README.html#features

**Comment by alanvardy** [comment]
That is really interesting. I am reading up on the details of supporting po files: https://hexdocs.pm/gettext/Gettext.html

But I think that going all the way with those files is outside of the scope of this library.

I'll check out the Pow solution.

**Comment by alanvardy** [comment]
Thank you for the issue @Sebi55 
0.4.0 is now released with Pow-style custom text. Let me know if you have any issues and I will make improvements.
