### ISSUE TITLE
Disable hide functionality

### ISSUE THREAD

**Issue by Sebi55** [alanvardy/exzeitable#209]
**Is your feature request related to a problem? Please describe.**
The current layout of the table including the allowed configuration options does not specify any option to disable the hide functionality. There are definitely tables where the user does not need to be able to hide columns of a table on the fly.

**Describe the solution you'd like**
I would like to have an option "disable_hide" which will remove all "hide" button on each column, and also remove the "show columns buttons" where I can reactivate hidden columns.

**Describe alternatives you've considered**
Currently I am using plain CSS to hide these fields. It is way cleaner to just not render or send this HTML to the user though.

**Additional context**
It is important that the "disable_hide" option does not disable the functionality to set columns to "hidden". There are tables where I do not show specific columns at all to the user but the search/query send from the table filter/search bar should still be able to query all this column.

**Comment by alanvardy** [comment]
:+1:
