### ISSUE TITLE
Add option to hide the top or bottom pagination

### ISSUE THREAD

**Issue by Sebi55** [alanvardy/exzeitable#210]
**Is your feature request related to a problem? Please describe.**
For esthetic I want to remove the top pagination as it looks very weird if the table is empty. Normal users are fine with one pagination at the bottom of the table.

**Describe the solution you'd like**
Add an option "hide_top/bottom_pagination" which will remove the pagination as specified.

**Describe alternatives you've considered**
I currently hide the top pagination via CSS by using the `:first-child` but it would be cleaner if they are not rendered into the HTML at all.

**Comment by alanvardy** [comment]
Good idea and easily implemented. I'll add this in the next round!
