### ISSUE TITLE
Customized text for "Preview/Next" in pagination and "sort" in column header

### ISSUE THREAD

**Issue by djabbar13** [alanvardy/exzeitable#218]
It would be better if we could put a custom text for "Next" and "Previous" in the pagination and also "sort" in the header of the sortable columns.
Thanks.

**Comment by Sebi55** [comment]
This is probably the same issue as the i18n feature as this would also allow you to replace the texts for the buttons.
#208

**Comment by alanvardy** [comment]
Thank you for the issue @djabbar13 

I have just released custom text functionality in 0.4.0. Please let me know if there are any issues!

**Comment by djabbar13** [comment]
Hi, thank you so much @alanvardy.
