### ISSUE TITLE
Make "Actions" header title of table translatable

### ISSUE THREAD

**Issue by Sebi55** [alanvardy/exzeitable#224]
**Is your feature request related to a problem? Please describe.**
As of the new version 0.4.0 nearly all buttons or texts are translatable except for the header bar "Actions" column.

**Describe the solution you'd like**
Include the "Actions" text in the default text file and make it customisable.

**Describe alternatives you've considered**
Implement a general option to translate all header columns for several languages. Will definitely be a bigger change than only the "Actions" text.

**Comment by alanvardy** [comment]
Your "Actions" text is now customizable and available in 0.4.1, thank you for the issue!

As for the header columns, is this a theoretical use case or are you needing multi-language support in your app?

**Comment by Sebi55** [comment]
I currently do not need all header titles to be translatable but would be a nice feature of course :)
