### ISSUE TITLE
Add option to disable / not include the Actions column

### ISSUE THREAD

**Issue by matt-riemer** [alanvardy/exzeitable#23]
I have an exzeitable with no actions.

I can pass `actions: []` so that no buttons are rendered, but that actions column is still there.

Could an option be added to not display the actions column at all?

Possibly `actions: false` 

Thanks!

**Comment by matt-riemer** [comment]
![Edit_Tradesway_Admins___Tradesway](https://user-images.githubusercontent.com/954468/67151806-5100ed00-f288-11e9-881a-04061db2f53d.png)

**Comment by matt-riemer** [comment]
![Edit_Tradesway_Admins___Tradesway](https://user-images.githubusercontent.com/954468/67151810-59592800-f288-11e9-9726-eb7050a48267.png)

**Comment by alanvardy** [comment]
Hi @matt-riemer, thank you for the issue!

I'll implement on the next PR, with `actions: []`
