### ISSUE TITLE
Searching for multiple words

### ISSUE THREAD

**Issue by greg-rychlewski** [alanvardy/exzeitable#246]
**Describe the bug**
When I search for multiple words, i.e. "post number", it doesn't return entries containing "post number".

**To Reproduce**
1. Clone this repo
2. Download dependencies/run migrations/insert seed data
3. Start app
4. Search for "post number"

**Expected behaviour**
Should see all entries containing "post number" under the column "title".

**Screenshots**
If I search for "post", it looks fine:

<img width="1154" alt="Screen Shot 2020-08-25 at 12 20 17 PM" src="https://user-images.githubusercontent.com/7695024/91200703-798a1c80-e6cd-11ea-83fb-ce3d5ef76392.png">

If I search for "post number", there are no entries:

<img width="1170" alt="Screen Shot 2020-08-25 at 12 20 25 PM" src="https://user-images.githubusercontent.com/7695024/91200732-8575de80-e6cd-11ea-9a62-b45b51bc8900.png">

**Additional context**
Looking at the source code, it seems like this is the culprit:

```
def prefix_search(term) do
  String.replace(term, ~r/\W|_/u, "") <> ":*"
end
```

It squishes all the words together and searches in the ts_vector for prefixes that match it. 

If you want to look for all the words, it looks like you need to first separate the words and then apply `:*` to each one and separate them by `&`. I'm happy to work on a PR if this is something you want changed.

**Comment by ekarak** [comment]
my personal take: the current behaviour is correct, we need to search on multiple terms on multiple fields. My gut feel as the best approach to solve this is to use double colons to denote literal terms to be searched in the same field eg `"post number" other_search_term` should yield two search terms, 'post number' and 'other_search_term'.

**Comment by greg-rychlewski** [comment]
Thinking as a user, I'm not sure how the current implementation is useful for me. 

If I type multiple words into a search bar, I wouldn't expect it to look for entries that are prefixed by the concatenation of all the words I entered. In most cases I imagine this would return nothing.

I would expect to find results that contain all the words in my search, in any order (see `plainto_tsquery` and similar psql functions [here](https://www.postgresql.org/docs/11/textsearch-controls.html)). 

The drawback of using quoted words is that you need to have it in exactly the right order. If I type `food dog` into a search and it didn't return entries that contain `dog food`, it would look strange.

In terms of what the correct behaviour should be, I see 3 choices:

1. Look for entries that contain all of the search words inside the concatenation of the search columns.
2. Look for entries that contain all of the search words in one of the search columns. This would involve creating a `tsvector` for each column and matching on them separately
3. Instead of using full text search, try to use the `pg_trgm` extension operators like `%`.

**Comment by alanvardy** [comment]
Hello! Thank you for the issue and I appreciate the discussion on this.

This is a valid problem as I think a user would expect the search to be able to handle spaces. I would err on the side of simplicity for the end user rather than the power/accuracy of the search. I'd also like the search to err on the greedy side as the user can simply continue entering characters if there are still too many results.

So while I feel that @ekarak 's solution may be more "correct", @greg-rychlewski 's solution #1 is probably the most intuitive for the average user.

I'm currently switching jobs and getting a kid ready for school, so I 100% appreciate any help! Please let me know how I can support you in creating a PR.

**Comment by greg-rychlewski** [comment]
Hi @alanvardy, I created a PR for you to review when you have the time.

Thanks for creating this library and good luck with your new job and your family.
