### ISSUE TITLE
Does not work within an existing live session or live view

### ISSUE THREAD

**Issue by atavistock** [alanvardy/exzeitable#374]
**Describe the bug**

Does not work from within an existing LiveView.  I believe this is because Exzeitable is expecting its own `mount` function to run, when any existing LiveView will likely have implemented this directly.  I believe this is exactly the reason they overhauled the lifecycle of mount with `on_mount`.

**To Reproduce**

Create a module with `use Exzeitable ...` per the documentation, but in the router put this under a `live_session` block and routed using `live`, using a browser go to the route.  

**Expected behaviour**

Should not fail due to missing assigns

**Comment by alanvardy** [comment]
Resolved with https://github.com/alanvardy/exzeitable/pull/377
