### ISSUE TITLE
Leveraging the Ash framework

### ISSUE THREAD

**Issue by mxgrn** [alanvardy/exzeitable#430]
It might leverage the [Ash framework](https://github.com/ash-project/ash) as a "backend" for configuring the underlying model, search, authorization, etc.

Not meaning to keep this issue open, but rather as a suggestion, or a place to discuss the idea. Thanks!

**Comment by alanvardy** [comment]
Hello @mxgrn , I don't have any plans to rewrite the backend at the moment but I am interested in hearing more about how this could improve Exzeitable :+1:

**Comment by mxgrn** [comment]
I just had an impression that Ash has a more powerful way of declaratively define the model, as well as all the operations behind that, effectively replacing Ecto. I'll close the issue for now, just wanted a heads-up for its existence, thanks for your time!

**Comment by alanvardy** [comment]
> I just had an impression that Ash has a more powerful way of declaratively define the model, as well as all the operations behind that, effectively replacing Ecto.

It very well may! I don't have enough context to be able to evaluate that. Thus far I've been a big fan of Ecto and whenever it was insufficient I was able to use its escape hatches and write some raw SQL. I'll keep an eye on Ash, thank you for dropping by!
