### ISSUE TITLE
Custom actions appear to be broken

### ISSUE THREAD

**Issue by superchris** [alanvardy/exzeitable#489]
When adding a custom action button, :foo, I get a crash

Steps to reproduce the behaviour:

1. Create a module that uses ExZeitable
2. Add a custom action :foo

I get: ** (FunctionClauseError) no function clause matching in Exzeitable.HTML.ActionButton.build/3

In looking at the code in action_button.ex the pattern for the fallthru that should delegate to the module function is not being satisfied. If I add my own build/3 function to log the output I can see it getting called.

**Comment by alanvardy** [comment]
Thank you for creating the issue! I'll look into this shortly :+1:

**Comment by alanvardy** [comment]
Fixed with 0.6.1, please let me know if the issue persists!
