### ISSUE TITLE
[Close Me] Neat, Thanks!

### ISSUE THREAD

**Issue by RobertLowe** [alanvardy/exzeitable#53]
I've been working on something nearly identical but it's going slow as I'm new to elixir, great to see someone is on the same track, great to compare approaches and patterns. Wanted a replacement for `ex_admin` using live views, seems like I'm not the only one! 

![Screen Shot 2019-11-16 at 3 42 02 AM](https://user-images.githubusercontent.com/601141/68990642-9b43a280-0823-11ea-9647-75ebc75d6928.png)

Mine is still WIP and I'll get it on github in the future.

In the meantime thanks for making this and pushing it to hex!

**Comment by alanvardy** [comment]
Hi @RobertLowe 

Fantastic! I really like your idea of grouping the results, and the funky dark theme. I have a private project that uses exzeitable extensively for all the datatables, and it makes the user experience a lot more enjoyable.

Can you drop me a line when you push to hex? I'd be very interested in seeing your work!

**Comment by RobertLowe** [comment]
Thanks. I got the idea for grouping results from: https://querybuilder.js.org/demo.html and the dark theme is from Dark Reader: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh inverting the page.

I'll drop a line once something is presentable!

**Comment by alanvardy** [comment]
Hi @RobertLowe, closing out the issue but really looking forward to hearing more once it is ready to see the light of day!
