### ISSUE TITLE
Phoenix LiveView 1.0.1 support

### ISSUE THREAD

**Issue by kishb87** [alanvardy/exzeitable#708]
**Is your feature request related to a problem? Please describe.**
The library is currently incompatible with the new Phx LiveView. 

**Describe the solution you'd like**
Upgrade library dependencies to support LiveView 1.0.

**Comment by alanvardy** [comment]
Thank you for the issue! I'll take a look into this :+1:

**Comment by alanvardy** [comment]
Resolved! Please update to 0.6.7 for LiveView 1.0 support.

**Comment by kishb87** [comment]
Wow, that was fast! Thank you!
